spring:
  data:
    mongodb:
      username: mongo
      host: localhost
      password: root
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      group-id: paymentGroup,orderGroup
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:dev.javokhir.ecommerce.kafka.OrderConfirmation, dev.javokhir.ecommerce.notification.PaymentNotificationRequest
      auto-offset-reset: earliest
  mail:
    host: localhost
    port: 1025
    username: mail
    password: root
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

  server:
    port: 8040